/** 歷史球隊（已降班／改制）隊徽靜態表：football-logos.cc 256px PNG，放 public/crests/。
 * 只作展示層後備：上游 API 對唔到名先用，對唔到再退派生盾形標。
 * Arles（已解散）庫入面冇，維持派生盾形標。 */
export const STATIC_CRESTS: Record<string, string> = {
  "E0|birmingham": "/crests/crest-e0-birmingham.png",
  "E0|blackburn": "/crests/crest-e0-blackburn.png",
  "E0|blackpool": "/crests/crest-e0-blackpool.png",
  "E0|bolton": "/crests/crest-e0-bolton.png",
  "E0|bradford": "/crests/crest-e0-bradford.png",
  "E0|burnley": "/crests/crest-e0-burnley.png",
  "E0|cardiff": "/crests/crest-e0-cardiff.png",
  "E0|charlton": "/crests/crest-e0-charlton.png",
  "E0|derby": "/crests/crest-e0-derby.png",
  "E0|huddersfield": "/crests/crest-e0-huddersfield.png",
  "E0|leicester": "/crests/crest-e0-leicester.png",
  "E0|luton": "/crests/crest-e0-luton.png",
  "E0|middlesbrough": "/crests/crest-e0-middlesbrough.png",
  "E0|norwich": "/crests/crest-e0-norwich.png",
  "E0|portsmouth": "/crests/crest-e0-portsmouth.png",
  "E0|qpr": "/crests/crest-e0-qpr.png",
  "E0|reading": "/crests/crest-e0-reading.png",
  "E0|sheffield united": "/crests/crest-e0-sheffield-united.png",
  "E0|southampton": "/crests/crest-e0-southampton.png",
  "E0|stoke": "/crests/crest-e0-stoke.png",
  "E0|swansea": "/crests/crest-e0-swansea.png",
  "E0|watford": "/crests/crest-e0-watford.png",
  "E0|west brom": "/crests/crest-e0-west-brom.png",
  "E0|west ham": "/crests/crest-e0-west-ham.png",
  "E0|wigan": "/crests/crest-e0-wigan.png",
  "E0|wolves": "/crests/crest-e0-wolves.png",
  "SP1|albacete": "/crests/crest-sp1-albacete.png",
  "SP1|almeria": "/crests/crest-sp1-almeria.png",
  "SP1|cadiz": "/crests/crest-sp1-cadiz.png",
  "SP1|cordoba": "/crests/crest-sp1-cordoba.png",
  "SP1|eibar": "/crests/crest-sp1-eibar.png",
  "SP1|gimnastic": "/crests/crest-sp1-gimnastic.png",
  "SP1|girona": "/crests/crest-sp1-girona.png",
  "SP1|granada": "/crests/crest-sp1-granada.png",
  "SP1|hercules": "/crests/crest-sp1-hercules.png",
  "SP1|huesca": "/crests/crest-sp1-huesca.png",
  "SP1|las palmas": "/crests/crest-sp1-las-palmas.png",
  "SP1|leganes": "/crests/crest-sp1-leganes.png",
  "SP1|mallorca": "/crests/crest-sp1-mallorca.png",
  "SP1|murcia": "/crests/crest-sp1-murcia.png",
  "SP1|numancia": "/crests/crest-sp1-numancia.png",
  "SP1|oviedo": "/crests/crest-sp1-oviedo.png",
  "SP1|recreativo": "/crests/crest-sp1-recreativo.png",
  "SP1|sp gijon": "/crests/crest-sp1-sp-gijon.png",
  "SP1|tenerife": "/crests/crest-sp1-tenerife.png",
  "SP1|valladolid": "/crests/crest-sp1-valladolid.png",
  "SP1|xerez": "/crests/crest-sp1-xerez.png",
  "SP1|zaragoza": "/crests/crest-sp1-zaragoza.png",
  "I1|ancona": "/crests/crest-i1-ancona.png",
  "I1|ascoli": "/crests/crest-i1-ascoli.png",
  "I1|bari": "/crests/crest-i1-bari.png",
  "I1|benevento": "/crests/crest-i1-benevento.png",
  "I1|brescia": "/crests/crest-i1-brescia.png",
  "I1|carpi": "/crests/crest-i1-carpi.png",
  "I1|catania": "/crests/crest-i1-catania.png",
  "I1|cesena": "/crests/crest-i1-cesena.png",
  "I1|chievo": "/crests/crest-i1-chievo.png",
  "I1|cremonese": "/crests/crest-i1-cremonese.png",
  "I1|crotone": "/crests/crest-i1-crotone.png",
  "I1|empoli": "/crests/crest-i1-empoli.png",
  "I1|livorno": "/crests/crest-i1-livorno.png",
  "I1|messina": "/crests/crest-i1-messina.png",
  "I1|modena": "/crests/crest-i1-modena.png",
  "I1|novara": "/crests/crest-i1-novara.png",
  "I1|palermo": "/crests/crest-i1-palermo.png",
  "I1|perugia": "/crests/crest-i1-perugia.png",
  "I1|pescara": "/crests/crest-i1-pescara.png",
  "I1|piacenza": "/crests/crest-i1-piacenza.png",
  "I1|pisa": "/crests/crest-i1-pisa.png",
  "I1|reggina": "/crests/crest-i1-reggina.png",
  "I1|salernitana": "/crests/crest-i1-salernitana.png",
  "I1|sampdoria": "/crests/crest-i1-sampdoria.png",
  "I1|siena": "/crests/crest-i1-siena.png",
  "I1|spal": "/crests/crest-i1-spal.png",
  "I1|spezia": "/crests/crest-i1-spezia.png",
  "I1|treviso": "/crests/crest-i1-treviso.png",
  "I1|verona": "/crests/crest-i1-verona.png",
  "I1|vicenza": "/crests/crest-i1-vicenza.png",
  "D1|aachen": "/crests/crest-d1-aachen.png",
  "D1|bielefeld": "/crests/crest-d1-bielefeld.png",
  "D1|bochum": "/crests/crest-d1-bochum.png",
  "D1|braunschweig": "/crests/crest-d1-braunschweig.png",
  "D1|cottbus": "/crests/crest-d1-cottbus.png",
  "D1|darmstadt": "/crests/crest-d1-darmstadt.png",
  "D1|duisburg": "/crests/crest-d1-duisburg.png",
  "D1|fortuna dusseldorf": "/crests/crest-d1-fortuna-dusseldorf.png",
  "D1|greuther furth": "/crests/crest-d1-greuther-furth.png",
  "D1|hannover": "/crests/crest-d1-hannover.png",
  "D1|hansa rostock": "/crests/crest-d1-hansa-rostock.png",
  "D1|heidenheim": "/crests/crest-d1-heidenheim.png",
  "D1|hertha": "/crests/crest-d1-hertha.png",
  "D1|holstein kiel": "/crests/crest-d1-holstein-kiel.png",
  "D1|ingolstadt": "/crests/crest-d1-ingolstadt.png",
  "D1|kaiserslautern": "/crests/crest-d1-kaiserslautern.png",
  "D1|karlsruhe": "/crests/crest-d1-karlsruhe.png",
  "D1|munich 1860": "/crests/crest-d1-munich-1860.png",
  "D1|nurnberg": "/crests/crest-d1-nurnberg.png",
  "D1|st pauli": "/crests/crest-d1-st-pauli.png",
  "D1|unterhaching": "/crests/crest-d1-unterhaching.png",
  "D1|wolfsburg": "/crests/crest-d1-wolfsburg.png",
  "F1|ajaccio": "/crests/crest-f1-ajaccio.png",
  "F1|ajaccio gfco": "/crests/crest-f1-ajaccio-gfco.png",
  "F1|amiens": "/crests/crest-f1-amiens.png",
  "F1|bastia": "/crests/crest-f1-bastia.png",
  "F1|bordeaux": "/crests/crest-f1-bordeaux.png",
  "F1|boulogne": "/crests/crest-f1-boulogne.png",
  "F1|caen": "/crests/crest-f1-caen.png",
  "F1|clermont": "/crests/crest-f1-clermont.png",
  "F1|dijon": "/crests/crest-f1-dijon.png",
  "F1|evian thonon gaillard": "/crests/crest-f1-evian-thonon-gaillard.png",
  "F1|grenoble": "/crests/crest-f1-grenoble.png",
  "F1|guingamp": "/crests/crest-f1-guingamp.png",
  "F1|istres": "/crests/crest-f1-istres.png",
  "F1|metz": "/crests/crest-f1-metz.png",
  "F1|montpellier": "/crests/crest-f1-montpellier.png",
  "F1|nancy": "/crests/crest-f1-nancy.png",
  "F1|nantes": "/crests/crest-f1-nantes.png",
  "F1|nimes": "/crests/crest-f1-nimes.png",
  "F1|reims": "/crests/crest-f1-reims.png",
  "F1|sedan": "/crests/crest-f1-sedan.png",
  "F1|sochaux": "/crests/crest-f1-sochaux.png",
  "F1|valenciennes": "/crests/crest-f1-valenciennes.png",
  // 次級聯賽（西乙／英甲／英乙／德乙／意乙／法乙，2024–2026 季）後備；Sudtirol 用維基百科官方徽
  "D2|bielefeld": "/crests/crest-d2-bielefeld.png",
  "D2|bochum": "/crests/crest-d2-bochum.png",
  "D2|braunschweig": "/crests/crest-d2-braunschweig.png",
  "D2|cottbus": "/crests/crest-d2-cottbus.png",
  "D2|darmstadt": "/crests/crest-d2-darmstadt.png",
  "D2|dresden": "/crests/crest-d2-dresden.png",
  "D2|elversberg": "/crests/crest-d2-elversberg.png",
  "D2|fc koln": "/crests/crest-d2-fc-koln.png",
  "D2|fortuna dusseldorf": "/crests/crest-d2-fortuna-dusseldorf.png",
  "D2|greuther furth": "/crests/crest-d2-greuther-furth.png",
  "D2|hamburg": "/crests/crest-d2-hamburg.png",
  "D2|hannover": "/crests/crest-d2-hannover.png",
  "D2|heidenheim": "/crests/crest-d2-heidenheim.png",
  "D2|hertha": "/crests/crest-d2-hertha.png",
  "D2|holstein kiel": "/crests/crest-d2-holstein-kiel.png",
  "D2|kaiserslautern": "/crests/crest-d2-kaiserslautern.png",
  "D2|karlsruhe": "/crests/crest-d2-karlsruhe.png",
  "D2|magdeburg": "/crests/crest-d2-magdeburg.png",
  "D2|nurnberg": "/crests/crest-d2-nurnberg.png",
  "D2|osnabruck": "/crests/crest-d2-osnabruck.png",
  "D2|paderborn": "/crests/crest-d2-paderborn.png",
  "D2|preußen münster": "/crests/crest-d2-preussen-munster.png",
  "D2|regensburg": "/crests/crest-d2-regensburg.png",
  "D2|schalke 04": "/crests/crest-d2-schalke-04.png",
  "D2|st pauli": "/crests/crest-d2-st-pauli.png",
  "D2|ulm": "/crests/crest-d2-ulm.png",
  "D2|wolfsburg": "/crests/crest-d2-wolfsburg.png",
  "E2|afc wimbledon": "/crests/crest-e2-afc-wimbledon.png",
  "E2|barnsley": "/crests/crest-e2-barnsley.png",
  "E2|birmingham": "/crests/crest-e2-birmingham.png",
  "E2|blackpool": "/crests/crest-e2-blackpool.png",
  "E2|bolton": "/crests/crest-e2-bolton.png",
  "E2|bradford": "/crests/crest-e2-bradford.png",
  "E2|bristol rvs": "/crests/crest-e2-bristol-rvs.png",
  "E2|bromley": "/crests/crest-e2-bromley.png",
  "E2|burton": "/crests/crest-e2-burton.png",
  "E2|cambridge": "/crests/crest-e2-cambridge.png",
  "E2|cardiff": "/crests/crest-e2-cardiff.png",
  "E2|charlton": "/crests/crest-e2-charlton.png",
  "E2|crawley town": "/crests/crest-e2-crawley-town.png",
  "E2|doncaster": "/crests/crest-e2-doncaster.png",
  "E2|exeter": "/crests/crest-e2-exeter.png",
  "E2|huddersfield": "/crests/crest-e2-huddersfield.png",
  "E2|leicester": "/crests/crest-e2-leicester.png",
  "E2|leyton orient": "/crests/crest-e2-leyton-orient.png",
  "E2|lincoln": "/crests/crest-e2-lincoln.png",
  "E2|luton": "/crests/crest-e2-luton.png",
  "E2|mansfield": "/crests/crest-e2-mansfield.png",
  "E2|milton keynes dons": "/crests/crest-e2-milton-keynes-dons.png",
  "E2|northampton": "/crests/crest-e2-northampton.png",
  "E2|notts county": "/crests/crest-e2-notts-county.png",
  "E2|oxford": "/crests/crest-e2-oxford.png",
  "E2|peterboro": "/crests/crest-e2-peterboro.png",
  "E2|plymouth": "/crests/crest-e2-plymouth.png",
  "E2|port vale": "/crests/crest-e2-port-vale.png",
  "E2|reading": "/crests/crest-e2-reading.png",
  "E2|rotherham": "/crests/crest-e2-rotherham.png",
  "E2|sheffield weds": "/crests/crest-e2-sheffield-weds.png",
  "E2|shrewsbury": "/crests/crest-e2-shrewsbury.png",
  "E2|stevenage": "/crests/crest-e2-stevenage.png",
  "E2|stockport": "/crests/crest-e2-stockport.png",
  "E2|wigan": "/crests/crest-e2-wigan.png",
  "E2|wrexham": "/crests/crest-e2-wrexham.png",
  "E2|wycombe": "/crests/crest-e2-wycombe.png",
  "E3|afc wimbledon": "/crests/crest-e3-afc-wimbledon.png",
  "E3|accrington": "/crests/crest-e3-accrington.png",
  "E3|barnet": "/crests/crest-e3-barnet.png",
  "E3|barrow": "/crests/crest-e3-barrow.png",
  "E3|bradford": "/crests/crest-e3-bradford.png",
  "E3|bristol rvs": "/crests/crest-e3-bristol-rvs.png",
  "E3|bromley": "/crests/crest-e3-bromley.png",
  "E3|cambridge": "/crests/crest-e3-cambridge.png",
  "E3|carlisle": "/crests/crest-e3-carlisle.png",
  "E3|cheltenham": "/crests/crest-e3-cheltenham.png",
  "E3|chesterfield": "/crests/crest-e3-chesterfield.png",
  "E3|colchester": "/crests/crest-e3-colchester.png",
  "E3|crawley town": "/crests/crest-e3-crawley-town.png",
  "E3|crewe": "/crests/crest-e3-crewe.png",
  "E3|doncaster": "/crests/crest-e3-doncaster.png",
  "E3|exeter": "/crests/crest-e3-exeter.png",
  "E3|fleetwood town": "/crests/crest-e3-fleetwood-town.png",
  "E3|gillingham": "/crests/crest-e3-gillingham.png",
  "E3|grimsby": "/crests/crest-e3-grimsby.png",
  "E3|harrogate": "/crests/crest-e3-harrogate.png",
  "E3|milton keynes dons": "/crests/crest-e3-milton-keynes-dons.png",
  "E3|morecambe": "/crests/crest-e3-morecambe.png",
  "E3|newport county": "/crests/crest-e3-newport-county.png",
  "E3|northampton": "/crests/crest-e3-northampton.png",
  "E3|notts county": "/crests/crest-e3-notts-county.png",
  "E3|oldham": "/crests/crest-e3-oldham.png",
  "E3|port vale": "/crests/crest-e3-port-vale.png",
  "E3|rochdale": "/crests/crest-e3-rochdale.png",
  "E3|rotherham": "/crests/crest-e3-rotherham.png",
  "E3|salford": "/crests/crest-e3-salford.png",
  "E3|shrewsbury": "/crests/crest-e3-shrewsbury.png",
  "E3|swindon": "/crests/crest-e3-swindon.png",
  "E3|tranmere": "/crests/crest-e3-tranmere.png",
  "E3|walsall": "/crests/crest-e3-walsall.png",
  "E3|york": "/crests/crest-e3-york.png",
  "F2|ajaccio": "/crests/crest-f2-ajaccio.png",
  "F2|amiens": "/crests/crest-f2-amiens.png",
  "F2|annecy": "/crests/crest-f2-annecy.png",
  "F2|bastia": "/crests/crest-f2-bastia.png",
  "F2|boulogne": "/crests/crest-f2-boulogne.png",
  "F2|caen": "/crests/crest-f2-caen.png",
  "F2|clermont": "/crests/crest-f2-clermont.png",
  "F2|dijon": "/crests/crest-f2-dijon.png",
  "F2|dunkerque": "/crests/crest-f2-dunkerque.png",
  "F2|grenoble": "/crests/crest-f2-grenoble.png",
  "F2|guingamp": "/crests/crest-f2-guingamp.png",
  "F2|laval": "/crests/crest-f2-laval.png",
  "F2|le mans": "/crests/crest-f2-le-mans.png",
  "F2|lorient": "/crests/crest-f2-lorient.png",
  "F2|martigues": "/crests/crest-f2-martigues.png",
  "F2|metz": "/crests/crest-f2-metz.png",
  "F2|montpellier": "/crests/crest-f2-montpellier.png",
  "F2|nancy": "/crests/crest-f2-nancy.png",
  "F2|nantes": "/crests/crest-f2-nantes.png",
  "F2|paris fc": "/crests/crest-f2-paris-fc.png",
  "F2|pau fc": "/crests/crest-f2-pau-fc.png",
  "F2|red star": "/crests/crest-f2-red-star.png",
  "F2|reims": "/crests/crest-f2-reims.png",
  "F2|rodez": "/crests/crest-f2-rodez.png",
  "F2|sochaux": "/crests/crest-f2-sochaux.png",
  "F2|st etienne": "/crests/crest-f2-st-etienne.png",
  "F2|troyes": "/crests/crest-f2-troyes.png",
  "I2|sudtirol": "/crests/crest-i2-sudtirol.png",
  "I2|arezzo": "/crests/crest-i2-arezzo.png",
  "I2|ascoli": "/crests/crest-i2-ascoli.png",
  "I2|avellino": "/crests/crest-i2-avellino.png",
  "I2|bari": "/crests/crest-i2-bari.png",
  "I2|benevento": "/crests/crest-i2-benevento.png",
  "I2|brescia": "/crests/crest-i2-brescia.png",
  "I2|carrarese": "/crests/crest-i2-carrarese.png",
  "I2|catanzaro": "/crests/crest-i2-catanzaro.png",
  "I2|cesena": "/crests/crest-i2-cesena.png",
  "I2|cittadella": "/crests/crest-i2-cittadella.png",
  "I2|cosenza": "/crests/crest-i2-cosenza.png",
  "I2|cremonese": "/crests/crest-i2-cremonese.png",
  "I2|empoli": "/crests/crest-i2-empoli.png",
  "I2|frosinone": "/crests/crest-i2-frosinone.png",
  "I2|juve stabia": "/crests/crest-i2-juve-stabia.png",
  "I2|mantova": "/crests/crest-i2-mantova.png",
  "I2|modena": "/crests/crest-i2-modena.png",
  "I2|monza": "/crests/crest-i2-monza.png",
  "I2|padova": "/crests/crest-i2-padova.png",
  "I2|palermo": "/crests/crest-i2-palermo.png",
  "I2|pescara": "/crests/crest-i2-pescara.png",
  "I2|pisa": "/crests/crest-i2-pisa.png",
  "I2|reggiana": "/crests/crest-i2-reggiana.png",
  "I2|salernitana": "/crests/crest-i2-salernitana.png",
  "I2|sampdoria": "/crests/crest-i2-sampdoria.png",
  "I2|sassuolo": "/crests/crest-i2-sassuolo.png",
  "I2|spezia": "/crests/crest-i2-spezia.png",
  "I2|venezia": "/crests/crest-i2-venezia.png",
  "I2|verona": "/crests/crest-i2-verona.png",
  "I2|vicenza": "/crests/crest-i2-vicenza.png",
  "I2|virtus entella": "/crests/crest-i2-virtus-entella.png",
  "SP2|albacete": "/crests/crest-sp2-albacete.png",
  "SP2|almeria": "/crests/crest-sp2-almeria.png",
  "SP2|andorra": "/crests/crest-sp2-andorra.png",
  "SP2|burgos": "/crests/crest-sp2-burgos.png",
  "SP2|cadiz": "/crests/crest-sp2-cadiz.png",
  "SP2|cartagena": "/crests/crest-sp2-cartagena.png",
  "SP2|castellon": "/crests/crest-sp2-castellon.png",
  "SP2|celta b": "/crests/crest-sp2-celta-b.png",
  "SP2|ceuta": "/crests/crest-sp2-ceuta.png",
  "SP2|cordoba": "/crests/crest-sp2-cordoba.png",
  "SP2|cultural leonesa": "/crests/crest-sp2-cultural-leonesa.png",
  "SP2|eibar": "/crests/crest-sp2-eibar.png",
  "SP2|elche": "/crests/crest-sp2-elche.png",
  "SP2|eldense": "/crests/crest-sp2-eldense.png",
  "SP2|ferrol": "/crests/crest-sp2-ferrol.png",
  "SP2|girona": "/crests/crest-sp2-girona.png",
  "SP2|granada": "/crests/crest-sp2-granada.png",
  "SP2|huesca": "/crests/crest-sp2-huesca.png",
  "SP2|la coruna": "/crests/crest-sp2-la-coruna.png",
  "SP2|las palmas": "/crests/crest-sp2-las-palmas.png",
  "SP2|leganes": "/crests/crest-sp2-leganes.png",
  "SP2|levante": "/crests/crest-sp2-levante.png",
  "SP2|malaga": "/crests/crest-sp2-malaga.png",
  "SP2|mallorca": "/crests/crest-sp2-mallorca.png",
  "SP2|mirandes": "/crests/crest-sp2-mirandes.png",
  "SP2|oviedo": "/crests/crest-sp2-oviedo.png",
  "SP2|sabadell": "/crests/crest-sp2-sabadell.png",
  "SP2|santander": "/crests/crest-sp2-santander.png",
  "SP2|sociedad b": "/crests/crest-sp2-sociedad-b.png",
  "SP2|sp gijon": "/crests/crest-sp2-sp-gijon.png",
  "SP2|tenerife": "/crests/crest-sp2-tenerife.png",
  "SP2|valladolid": "/crests/crest-sp2-valladolid.png",
  "SP2|zaragoza": "/crests/crest-sp2-zaragoza.png",
};
