/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DevLogRouteImport } from './routes/dev-log'
import { Route as EncyclopediaRouteImport } from './routes/encyclopedia'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FreezeLedgerRouteImport } from './routes/freeze-ledger'
import { Route as HorseRouteImport } from './routes/horse'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as MarksixRouteImport } from './routes/marksix'
import { Route as MarksixResultsRouteImport } from './routes/marksix-results'
import { Route as MediaCreditsRouteImport } from './routes/media-credits'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as PoolOddsRouteImport } from './routes/pool-odds'
import { Route as PredictionVsResultRouteImport } from './routes/prediction-vs-result'
import { Route as PredictorRouteImport } from './routes/predictor'
import { Route as RaceRouteImport } from './routes/race'
import { Route as RacingHealthRouteImport } from './routes/racing-health'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as StrategyPnlRouteImport } from './routes/strategy-pnl'
import { Route as TrackRecordRouteImport } from './routes/track-record'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as EngineIndexRouteImport } from './routes/engine.index'
import { Route as EngineBacktestRouteImport } from './routes/engine.backtest'
import { Route as EngineFeaturesRouteImport } from './routes/engine.features'
import { Route as EngineMonitorRouteImport } from './routes/engine.monitor'
import { Route as EngineResidualsRouteImport } from './routes/engine.residuals'
import { Route as ExplainIndexRouteImport } from './routes/explain.index'
import { Route as ExplainDateRouteImport } from './routes/explain.$date'
import { Route as FootballIndexRouteImport } from './routes/football.index'
import { Route as FootballDualLedgerRouteImport } from './routes/football.dual-ledger'
import { Route as FootballEngineRouteImport } from './routes/football.engine'
import { Route as FootballExplainRouteImport } from './routes/football.explain'
import { Route as FootballFeaturesRouteImport } from './routes/football.features'
import { Route as FootballFixturesRouteImport } from './routes/football.fixtures'
import { Route as FootballIngestStatusRouteImport } from './routes/football.ingest-status'
import { Route as FootballMatchVsResultRouteImport } from './routes/football.match-vs-result'
import { Route as FootballPredictionVsResultRouteImport } from './routes/football.prediction-vs-result'
import { Route as FootballResultsRouteImport } from './routes/football.results'
import { Route as FootballStandingsRouteImport } from './routes/football.standings'
import { Route as FootballStudyRouteImport } from './routes/football.study'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminConsoleRouteImport } from './routes/_authenticated/admin.console'
import { Route as AuthenticatedAdminDataFreshnessRouteImport } from './routes/_authenticated/admin.data-freshness'
import { Route as AuthenticatedAdminEngineHealthRouteImport } from './routes/_authenticated/admin.engine-health'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin.logs'
import { Route as AuthenticatedAdminModelVersionsRouteImport } from './routes/_authenticated/admin.model-versions'
import { Route as AuthenticatedAdminOverviewRouteImport } from './routes/_authenticated/admin.overview'
import { Route as AuthenticatedAdminPnlRouteImport } from './routes/_authenticated/admin.pnl'
import { Route as AuthenticatedAdminPredictionLockRouteImport } from './routes/_authenticated/admin.prediction-lock'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminUsersMembershipRouteImport } from './routes/_authenticated/admin.users-membership'
import { Route as ApiPublicDataMirrorRouteImport } from './routes/api/public/data-mirror'
import { Route as ApiPublicDrawTuneRouteImport } from './routes/api/public/draw-tune'
import { Route as ApiPublicEngineHealthRouteImport } from './routes/api/public/engine-health'
import { Route as ApiPublicFootballCrestsRouteImport } from './routes/api/public/football-crests'
import { Route as ApiPublicFootballDualLockRouteImport } from './routes/api/public/football-dual-lock'
import { Route as ApiPublicFootballHkjcListRouteImport } from './routes/api/public/football-hkjc-list'
import { Route as ApiPublicFootballIngestStatusRouteImport } from './routes/api/public/football-ingest-status'
import { Route as ApiPublicFootballLeagueRouteImport } from './routes/api/public/football-league'
import { Route as ApiPublicFootballLineupSettleRouteImport } from './routes/api/public/football-lineup-settle'
import { Route as ApiPublicFootballLiveRouteImport } from './routes/api/public/football-live'
import { Route as ApiPublicFootballLiveResultsRouteImport } from './routes/api/public/football-live-results'
import { Route as ApiPublicFootballNewsRouteImport } from './routes/api/public/football-news'
import { Route as ApiPublicFootballPitchapiProbeRouteImport } from './routes/api/public/football-pitchapi-probe'
import { Route as ApiPublicFootballPlayerSourceCheckRouteImport } from './routes/api/public/football-player-source-check'
import { Route as ApiPublicFootballPredictionsRouteImport } from './routes/api/public/football-predictions'
import { Route as ApiPublicFootballSourceCheckRouteImport } from './routes/api/public/football-source-check'
import { Route as ApiPublicFreezeLedgerRouteImport } from './routes/api/public/freeze-ledger'
import { Route as ApiPublicHkjcWeatherRouteImport } from './routes/api/public/hkjc-weather'
import { Route as ApiPublicHorseHr2RouteImport } from './routes/api/public/horse-hr2'
import { Route as ApiPublicLockStateRouteImport } from './routes/api/public/lock-state'
import { Route as ApiPublicMarksixDataRouteImport } from './routes/api/public/marksix-data'
import { Route as ApiPublicMarksixNextRouteImport } from './routes/api/public/marksix-next'
import { Route as ApiPublicMeetingCancellationRouteImport } from './routes/api/public/meeting-cancellation'
import { Route as ApiPublicTelegramAlertRouteImport } from './routes/api/public/telegram-alert'
import { Route as ApiPublicWeatherArchiveRouteImport } from './routes/api/public/weather-archive'
import { Route as ApiPublicWeatherSyncGithubRouteImport } from './routes/api/public/weather-sync-github'
import { Route as FootballMatchMatchKeyRouteImport } from './routes/football.match.$matchKey'
import { Route as FootballStudyMatchIdRouteImport } from './routes/football.study.$matchId'
import { Route as ApiPublicHooksRaceResultsDispatchRouteImport } from './routes/api/public/hooks/race-results-dispatch'
import { Route as FootballTeamDivSlugRouteImport } from './routes/football.team.$div.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DevLogRoute = DevLogRouteImport.update({
  id: '/dev-log',
  path: '/dev-log',
  getParentRoute: () => rootRouteImport,
} as any)
const EncyclopediaRoute = EncyclopediaRouteImport.update({
  id: '/encyclopedia',
  path: '/encyclopedia',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FreezeLedgerRoute = FreezeLedgerRouteImport.update({
  id: '/freeze-ledger',
  path: '/freeze-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const HorseRoute = HorseRouteImport.update({
  id: '/horse',
  path: '/horse',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const MarksixRoute = MarksixRouteImport.update({
  id: '/marksix',
  path: '/marksix',
  getParentRoute: () => rootRouteImport,
} as any)
const MarksixResultsRoute = MarksixResultsRouteImport.update({
  id: '/marksix-results',
  path: '/marksix-results',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaCreditsRoute = MediaCreditsRouteImport.update({
  id: '/media-credits',
  path: '/media-credits',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolOddsRoute = PoolOddsRouteImport.update({
  id: '/pool-odds',
  path: '/pool-odds',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionVsResultRoute = PredictionVsResultRouteImport.update({
  id: '/prediction-vs-result',
  path: '/prediction-vs-result',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictorRoute = PredictorRouteImport.update({
  id: '/predictor',
  path: '/predictor',
  getParentRoute: () => rootRouteImport,
} as any)
const RaceRoute = RaceRouteImport.update({
  id: '/race',
  path: '/race',
  getParentRoute: () => rootRouteImport,
} as any)
const RacingHealthRoute = RacingHealthRouteImport.update({
  id: '/racing-health',
  path: '/racing-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyPnlRoute = StrategyPnlRouteImport.update({
  id: '/strategy-pnl',
  path: '/strategy-pnl',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRecordRoute = TrackRecordRouteImport.update({
  id: '/track-record',
  path: '/track-record',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EngineIndexRoute = EngineIndexRouteImport.update({
  id: '/engine/',
  path: '/engine/',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineBacktestRoute = EngineBacktestRouteImport.update({
  id: '/engine/backtest',
  path: '/engine/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineFeaturesRoute = EngineFeaturesRouteImport.update({
  id: '/engine/features',
  path: '/engine/features',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineMonitorRoute = EngineMonitorRouteImport.update({
  id: '/engine/monitor',
  path: '/engine/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineResidualsRoute = EngineResidualsRouteImport.update({
  id: '/engine/residuals',
  path: '/engine/residuals',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainIndexRoute = ExplainIndexRouteImport.update({
  id: '/explain/',
  path: '/explain/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainDateRoute = ExplainDateRouteImport.update({
  id: '/explain/$date',
  path: '/explain/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const FootballIndexRoute = FootballIndexRouteImport.update({
  id: '/football/',
  path: '/football/',
  getParentRoute: () => rootRouteImport,
} as any)
const FootballDualLedgerRoute = FootballDualLedgerRouteImport.update({
  id: '/football/dual-ledger',
  path: '/football/dual-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const FootballEngineRoute = FootballEngineRouteImport.update({
  id: '/football/engine',
  path: '/football/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const FootballExplainRoute = FootballExplainRouteImport.update({
  id: '/football/explain',
  path: '/football/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const FootballFeaturesRoute = FootballFeaturesRouteImport.update({
  id: '/football/features',
  path: '/football/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FootballFixturesRoute = FootballFixturesRouteImport.update({
  id: '/football/fixtures',
  path: '/football/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const FootballIngestStatusRoute = FootballIngestStatusRouteImport.update({
  id: '/football/ingest-status',
  path: '/football/ingest-status',
  getParentRoute: () => rootRouteImport,
} as any)
const FootballMatchVsResultRoute = FootballMatchVsResultRouteImport.update({
  id: '/football/match-vs-result',
  path: '/football/match-vs-result',
  getParentRoute: () => rootRouteImport,
} as any)
const FootballPredictionVsResultRoute =
  FootballPredictionVsResultRouteImport.update({
    id: '/football/prediction-vs-result',
    path: '/football/prediction-vs-result',
    getParentRoute: () => rootRouteImport,
  } as any)
const FootballResultsRoute = FootballResultsRouteImport.update({
  id: '/football/results',
  path: '/football/results',
  getParentRoute: () => rootRouteImport,
} as any)
const FootballStandingsRoute = FootballStandingsRouteImport.update({
  id: '/football/standings',
  path: '/football/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const FootballStudyRoute = FootballStudyRouteImport.update({
  id: '/football/study',
  path: '/football/study',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminConsoleRoute =
  AuthenticatedAdminConsoleRouteImport.update({
    id: '/console',
    path: '/console',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDataFreshnessRoute =
  AuthenticatedAdminDataFreshnessRouteImport.update({
    id: '/data-freshness',
    path: '/data-freshness',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEngineHealthRoute =
  AuthenticatedAdminEngineHealthRouteImport.update({
    id: '/engine-health',
    path: '/engine-health',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminModelVersionsRoute =
  AuthenticatedAdminModelVersionsRouteImport.update({
    id: '/model-versions',
    path: '/model-versions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOverviewRoute =
  AuthenticatedAdminOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPnlRoute = AuthenticatedAdminPnlRouteImport.update({
  id: '/pnl',
  path: '/pnl',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPredictionLockRoute =
  AuthenticatedAdminPredictionLockRouteImport.update({
    id: '/prediction-lock',
    path: '/prediction-lock',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersMembershipRoute =
  AuthenticatedAdminUsersMembershipRouteImport.update({
    id: '/users-membership',
    path: '/users-membership',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicDataMirrorRoute = ApiPublicDataMirrorRouteImport.update({
  id: '/api/public/data-mirror',
  path: '/api/public/data-mirror',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDrawTuneRoute = ApiPublicDrawTuneRouteImport.update({
  id: '/api/public/draw-tune',
  path: '/api/public/draw-tune',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEngineHealthRoute = ApiPublicEngineHealthRouteImport.update({
  id: '/api/public/engine-health',
  path: '/api/public/engine-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFootballCrestsRoute = ApiPublicFootballCrestsRouteImport.update({
  id: '/api/public/football-crests',
  path: '/api/public/football-crests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFootballDualLockRoute =
  ApiPublicFootballDualLockRouteImport.update({
    id: '/api/public/football-dual-lock',
    path: '/api/public/football-dual-lock',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFootballHkjcListRoute =
  ApiPublicFootballHkjcListRouteImport.update({
    id: '/api/public/football-hkjc-list',
    path: '/api/public/football-hkjc-list',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFootballIngestStatusRoute =
  ApiPublicFootballIngestStatusRouteImport.update({
    id: '/api/public/football-ingest-status',
    path: '/api/public/football-ingest-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFootballLeagueRoute = ApiPublicFootballLeagueRouteImport.update({
  id: '/api/public/football-league',
  path: '/api/public/football-league',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFootballLineupSettleRoute =
  ApiPublicFootballLineupSettleRouteImport.update({
    id: '/api/public/football-lineup-settle',
    path: '/api/public/football-lineup-settle',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFootballLiveRoute = ApiPublicFootballLiveRouteImport.update({
  id: '/api/public/football-live',
  path: '/api/public/football-live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFootballLiveResultsRoute =
  ApiPublicFootballLiveResultsRouteImport.update({
    id: '/api/public/football-live-results',
    path: '/api/public/football-live-results',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFootballNewsRoute = ApiPublicFootballNewsRouteImport.update({
  id: '/api/public/football-news',
  path: '/api/public/football-news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFootballPitchapiProbeRoute =
  ApiPublicFootballPitchapiProbeRouteImport.update({
    id: '/api/public/football-pitchapi-probe',
    path: '/api/public/football-pitchapi-probe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFootballPlayerSourceCheckRoute =
  ApiPublicFootballPlayerSourceCheckRouteImport.update({
    id: '/api/public/football-player-source-check',
    path: '/api/public/football-player-source-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFootballPredictionsRoute =
  ApiPublicFootballPredictionsRouteImport.update({
    id: '/api/public/football-predictions',
    path: '/api/public/football-predictions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFootballSourceCheckRoute =
  ApiPublicFootballSourceCheckRouteImport.update({
    id: '/api/public/football-source-check',
    path: '/api/public/football-source-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFreezeLedgerRoute = ApiPublicFreezeLedgerRouteImport.update({
  id: '/api/public/freeze-ledger',
  path: '/api/public/freeze-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHkjcWeatherRoute = ApiPublicHkjcWeatherRouteImport.update({
  id: '/api/public/hkjc-weather',
  path: '/api/public/hkjc-weather',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHorseHr2Route = ApiPublicHorseHr2RouteImport.update({
  id: '/api/public/horse-hr2',
  path: '/api/public/horse-hr2',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLockStateRoute = ApiPublicLockStateRouteImport.update({
  id: '/api/public/lock-state',
  path: '/api/public/lock-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarksixDataRoute = ApiPublicMarksixDataRouteImport.update({
  id: '/api/public/marksix-data',
  path: '/api/public/marksix-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarksixNextRoute = ApiPublicMarksixNextRouteImport.update({
  id: '/api/public/marksix-next',
  path: '/api/public/marksix-next',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMeetingCancellationRoute =
  ApiPublicMeetingCancellationRouteImport.update({
    id: '/api/public/meeting-cancellation',
    path: '/api/public/meeting-cancellation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramAlertRoute = ApiPublicTelegramAlertRouteImport.update({
  id: '/api/public/telegram-alert',
  path: '/api/public/telegram-alert',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWeatherArchiveRoute = ApiPublicWeatherArchiveRouteImport.update({
  id: '/api/public/weather-archive',
  path: '/api/public/weather-archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWeatherSyncGithubRoute =
  ApiPublicWeatherSyncGithubRouteImport.update({
    id: '/api/public/weather-sync-github',
    path: '/api/public/weather-sync-github',
    getParentRoute: () => rootRouteImport,
  } as any)
const FootballMatchMatchKeyRoute = FootballMatchMatchKeyRouteImport.update({
  id: '/football/match/$matchKey',
  path: '/football/match/$matchKey',
  getParentRoute: () => rootRouteImport,
} as any)
const FootballStudyMatchIdRoute = FootballStudyMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => FootballStudyRoute,
} as any)
const ApiPublicHooksRaceResultsDispatchRoute =
  ApiPublicHooksRaceResultsDispatchRouteImport.update({
    id: '/api/public/hooks/race-results-dispatch',
    path: '/api/public/hooks/race-results-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const FootballTeamDivSlugRoute = FootballTeamDivSlugRouteImport.update({
  id: '/football/team/$div/$slug',
  path: '/football/team/$div/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/dev-log': typeof DevLogRoute
  '/encyclopedia': typeof EncyclopediaRoute
  '/features': typeof FeaturesRoute
  '/freeze-ledger': typeof FreezeLedgerRoute
  '/horse': typeof HorseRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/marksix': typeof MarksixRoute
  '/marksix-results': typeof MarksixResultsRoute
  '/media-credits': typeof MediaCreditsRoute
  '/membership': typeof MembershipRoute
  '/pool-odds': typeof PoolOddsRoute
  '/prediction-vs-result': typeof PredictionVsResultRoute
  '/predictor': typeof PredictorRoute
  '/race': typeof RaceRoute
  '/racing-health': typeof RacingHealthRoute
  '/results': typeof ResultsRoute
  '/schedule': typeof ScheduleRoute
  '/strategy-pnl': typeof StrategyPnlRoute
  '/track-record': typeof TrackRecordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/engine/backtest': typeof EngineBacktestRoute
  '/engine/features': typeof EngineFeaturesRoute
  '/engine/monitor': typeof EngineMonitorRoute
  '/engine/residuals': typeof EngineResidualsRoute
  '/explain/$date': typeof ExplainDateRoute
  '/football/dual-ledger': typeof FootballDualLedgerRoute
  '/football/engine': typeof FootballEngineRoute
  '/football/explain': typeof FootballExplainRoute
  '/football/features': typeof FootballFeaturesRoute
  '/football/fixtures': typeof FootballFixturesRoute
  '/football/ingest-status': typeof FootballIngestStatusRoute
  '/football/match-vs-result': typeof FootballMatchVsResultRoute
  '/football/prediction-vs-result': typeof FootballPredictionVsResultRoute
  '/football/results': typeof FootballResultsRoute
  '/football/standings': typeof FootballStandingsRoute
  '/football/study': typeof FootballStudyRouteWithChildren
  '/engine/': typeof EngineIndexRoute
  '/explain/': typeof ExplainIndexRoute
  '/football/': typeof FootballIndexRoute
  '/admin/console': typeof AuthenticatedAdminConsoleRoute
  '/admin/data-freshness': typeof AuthenticatedAdminDataFreshnessRoute
  '/admin/engine-health': typeof AuthenticatedAdminEngineHealthRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/model-versions': typeof AuthenticatedAdminModelVersionsRoute
  '/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/admin/pnl': typeof AuthenticatedAdminPnlRoute
  '/admin/prediction-lock': typeof AuthenticatedAdminPredictionLockRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users-membership': typeof AuthenticatedAdminUsersMembershipRoute
  '/api/public/data-mirror': typeof ApiPublicDataMirrorRoute
  '/api/public/draw-tune': typeof ApiPublicDrawTuneRoute
  '/api/public/engine-health': typeof ApiPublicEngineHealthRoute
  '/api/public/football-crests': typeof ApiPublicFootballCrestsRoute
  '/api/public/football-dual-lock': typeof ApiPublicFootballDualLockRoute
  '/api/public/football-hkjc-list': typeof ApiPublicFootballHkjcListRoute
  '/api/public/football-ingest-status': typeof ApiPublicFootballIngestStatusRoute
  '/api/public/football-league': typeof ApiPublicFootballLeagueRoute
  '/api/public/football-lineup-settle': typeof ApiPublicFootballLineupSettleRoute
  '/api/public/football-live': typeof ApiPublicFootballLiveRoute
  '/api/public/football-live-results': typeof ApiPublicFootballLiveResultsRoute
  '/api/public/football-news': typeof ApiPublicFootballNewsRoute
  '/api/public/football-pitchapi-probe': typeof ApiPublicFootballPitchapiProbeRoute
  '/api/public/football-player-source-check': typeof ApiPublicFootballPlayerSourceCheckRoute
  '/api/public/football-predictions': typeof ApiPublicFootballPredictionsRoute
  '/api/public/football-source-check': typeof ApiPublicFootballSourceCheckRoute
  '/api/public/freeze-ledger': typeof ApiPublicFreezeLedgerRoute
  '/api/public/hkjc-weather': typeof ApiPublicHkjcWeatherRoute
  '/api/public/horse-hr2': typeof ApiPublicHorseHr2Route
  '/api/public/lock-state': typeof ApiPublicLockStateRoute
  '/api/public/marksix-data': typeof ApiPublicMarksixDataRoute
  '/api/public/marksix-next': typeof ApiPublicMarksixNextRoute
  '/api/public/meeting-cancellation': typeof ApiPublicMeetingCancellationRoute
  '/api/public/telegram-alert': typeof ApiPublicTelegramAlertRoute
  '/api/public/weather-archive': typeof ApiPublicWeatherArchiveRoute
  '/api/public/weather-sync-github': typeof ApiPublicWeatherSyncGithubRoute
  '/football/match/$matchKey': typeof FootballMatchMatchKeyRoute
  '/football/study/$matchId': typeof FootballStudyMatchIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/race-results-dispatch': typeof ApiPublicHooksRaceResultsDispatchRoute
  '/football/team/$div/$slug': typeof FootballTeamDivSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/dev-log': typeof DevLogRoute
  '/encyclopedia': typeof EncyclopediaRoute
  '/features': typeof FeaturesRoute
  '/freeze-ledger': typeof FreezeLedgerRoute
  '/horse': typeof HorseRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/marksix': typeof MarksixRoute
  '/marksix-results': typeof MarksixResultsRoute
  '/media-credits': typeof MediaCreditsRoute
  '/membership': typeof MembershipRoute
  '/pool-odds': typeof PoolOddsRoute
  '/prediction-vs-result': typeof PredictionVsResultRoute
  '/predictor': typeof PredictorRoute
  '/race': typeof RaceRoute
  '/racing-health': typeof RacingHealthRoute
  '/results': typeof ResultsRoute
  '/schedule': typeof ScheduleRoute
  '/strategy-pnl': typeof StrategyPnlRoute
  '/track-record': typeof TrackRecordRoute
  '/engine/backtest': typeof EngineBacktestRoute
  '/engine/features': typeof EngineFeaturesRoute
  '/engine/monitor': typeof EngineMonitorRoute
  '/engine/residuals': typeof EngineResidualsRoute
  '/explain/$date': typeof ExplainDateRoute
  '/football/dual-ledger': typeof FootballDualLedgerRoute
  '/football/engine': typeof FootballEngineRoute
  '/football/explain': typeof FootballExplainRoute
  '/football/features': typeof FootballFeaturesRoute
  '/football/fixtures': typeof FootballFixturesRoute
  '/football/ingest-status': typeof FootballIngestStatusRoute
  '/football/match-vs-result': typeof FootballMatchVsResultRoute
  '/football/prediction-vs-result': typeof FootballPredictionVsResultRoute
  '/football/results': typeof FootballResultsRoute
  '/football/standings': typeof FootballStandingsRoute
  '/football/study': typeof FootballStudyRouteWithChildren
  '/engine': typeof EngineIndexRoute
  '/explain': typeof ExplainIndexRoute
  '/football': typeof FootballIndexRoute
  '/admin/console': typeof AuthenticatedAdminConsoleRoute
  '/admin/data-freshness': typeof AuthenticatedAdminDataFreshnessRoute
  '/admin/engine-health': typeof AuthenticatedAdminEngineHealthRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/model-versions': typeof AuthenticatedAdminModelVersionsRoute
  '/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/admin/pnl': typeof AuthenticatedAdminPnlRoute
  '/admin/prediction-lock': typeof AuthenticatedAdminPredictionLockRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users-membership': typeof AuthenticatedAdminUsersMembershipRoute
  '/api/public/data-mirror': typeof ApiPublicDataMirrorRoute
  '/api/public/draw-tune': typeof ApiPublicDrawTuneRoute
  '/api/public/engine-health': typeof ApiPublicEngineHealthRoute
  '/api/public/football-crests': typeof ApiPublicFootballCrestsRoute
  '/api/public/football-dual-lock': typeof ApiPublicFootballDualLockRoute
  '/api/public/football-hkjc-list': typeof ApiPublicFootballHkjcListRoute
  '/api/public/football-ingest-status': typeof ApiPublicFootballIngestStatusRoute
  '/api/public/football-league': typeof ApiPublicFootballLeagueRoute
  '/api/public/football-lineup-settle': typeof ApiPublicFootballLineupSettleRoute
  '/api/public/football-live': typeof ApiPublicFootballLiveRoute
  '/api/public/football-live-results': typeof ApiPublicFootballLiveResultsRoute
  '/api/public/football-news': typeof ApiPublicFootballNewsRoute
  '/api/public/football-pitchapi-probe': typeof ApiPublicFootballPitchapiProbeRoute
  '/api/public/football-player-source-check': typeof ApiPublicFootballPlayerSourceCheckRoute
  '/api/public/football-predictions': typeof ApiPublicFootballPredictionsRoute
  '/api/public/football-source-check': typeof ApiPublicFootballSourceCheckRoute
  '/api/public/freeze-ledger': typeof ApiPublicFreezeLedgerRoute
  '/api/public/hkjc-weather': typeof ApiPublicHkjcWeatherRoute
  '/api/public/horse-hr2': typeof ApiPublicHorseHr2Route
  '/api/public/lock-state': typeof ApiPublicLockStateRoute
  '/api/public/marksix-data': typeof ApiPublicMarksixDataRoute
  '/api/public/marksix-next': typeof ApiPublicMarksixNextRoute
  '/api/public/meeting-cancellation': typeof ApiPublicMeetingCancellationRoute
  '/api/public/telegram-alert': typeof ApiPublicTelegramAlertRoute
  '/api/public/weather-archive': typeof ApiPublicWeatherArchiveRoute
  '/api/public/weather-sync-github': typeof ApiPublicWeatherSyncGithubRoute
  '/football/match/$matchKey': typeof FootballMatchMatchKeyRoute
  '/football/study/$matchId': typeof FootballStudyMatchIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/race-results-dispatch': typeof ApiPublicHooksRaceResultsDispatchRoute
  '/football/team/$div/$slug': typeof FootballTeamDivSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/dev-log': typeof DevLogRoute
  '/encyclopedia': typeof EncyclopediaRoute
  '/features': typeof FeaturesRoute
  '/freeze-ledger': typeof FreezeLedgerRoute
  '/horse': typeof HorseRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/marksix': typeof MarksixRoute
  '/marksix-results': typeof MarksixResultsRoute
  '/media-credits': typeof MediaCreditsRoute
  '/membership': typeof MembershipRoute
  '/pool-odds': typeof PoolOddsRoute
  '/prediction-vs-result': typeof PredictionVsResultRoute
  '/predictor': typeof PredictorRoute
  '/race': typeof RaceRoute
  '/racing-health': typeof RacingHealthRoute
  '/results': typeof ResultsRoute
  '/schedule': typeof ScheduleRoute
  '/strategy-pnl': typeof StrategyPnlRoute
  '/track-record': typeof TrackRecordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/engine/backtest': typeof EngineBacktestRoute
  '/engine/features': typeof EngineFeaturesRoute
  '/engine/monitor': typeof EngineMonitorRoute
  '/engine/residuals': typeof EngineResidualsRoute
  '/explain/$date': typeof ExplainDateRoute
  '/football/dual-ledger': typeof FootballDualLedgerRoute
  '/football/engine': typeof FootballEngineRoute
  '/football/explain': typeof FootballExplainRoute
  '/football/features': typeof FootballFeaturesRoute
  '/football/fixtures': typeof FootballFixturesRoute
  '/football/ingest-status': typeof FootballIngestStatusRoute
  '/football/match-vs-result': typeof FootballMatchVsResultRoute
  '/football/prediction-vs-result': typeof FootballPredictionVsResultRoute
  '/football/results': typeof FootballResultsRoute
  '/football/standings': typeof FootballStandingsRoute
  '/football/study': typeof FootballStudyRouteWithChildren
  '/engine/': typeof EngineIndexRoute
  '/explain/': typeof ExplainIndexRoute
  '/football/': typeof FootballIndexRoute
  '/_authenticated/admin/console': typeof AuthenticatedAdminConsoleRoute
  '/_authenticated/admin/data-freshness': typeof AuthenticatedAdminDataFreshnessRoute
  '/_authenticated/admin/engine-health': typeof AuthenticatedAdminEngineHealthRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/model-versions': typeof AuthenticatedAdminModelVersionsRoute
  '/_authenticated/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/_authenticated/admin/pnl': typeof AuthenticatedAdminPnlRoute
  '/_authenticated/admin/prediction-lock': typeof AuthenticatedAdminPredictionLockRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users-membership': typeof AuthenticatedAdminUsersMembershipRoute
  '/api/public/data-mirror': typeof ApiPublicDataMirrorRoute
  '/api/public/draw-tune': typeof ApiPublicDrawTuneRoute
  '/api/public/engine-health': typeof ApiPublicEngineHealthRoute
  '/api/public/football-crests': typeof ApiPublicFootballCrestsRoute
  '/api/public/football-dual-lock': typeof ApiPublicFootballDualLockRoute
  '/api/public/football-hkjc-list': typeof ApiPublicFootballHkjcListRoute
  '/api/public/football-ingest-status': typeof ApiPublicFootballIngestStatusRoute
  '/api/public/football-league': typeof ApiPublicFootballLeagueRoute
  '/api/public/football-lineup-settle': typeof ApiPublicFootballLineupSettleRoute
  '/api/public/football-live': typeof ApiPublicFootballLiveRoute
  '/api/public/football-live-results': typeof ApiPublicFootballLiveResultsRoute
  '/api/public/football-news': typeof ApiPublicFootballNewsRoute
  '/api/public/football-pitchapi-probe': typeof ApiPublicFootballPitchapiProbeRoute
  '/api/public/football-player-source-check': typeof ApiPublicFootballPlayerSourceCheckRoute
  '/api/public/football-predictions': typeof ApiPublicFootballPredictionsRoute
  '/api/public/football-source-check': typeof ApiPublicFootballSourceCheckRoute
  '/api/public/freeze-ledger': typeof ApiPublicFreezeLedgerRoute
  '/api/public/hkjc-weather': typeof ApiPublicHkjcWeatherRoute
  '/api/public/horse-hr2': typeof ApiPublicHorseHr2Route
  '/api/public/lock-state': typeof ApiPublicLockStateRoute
  '/api/public/marksix-data': typeof ApiPublicMarksixDataRoute
  '/api/public/marksix-next': typeof ApiPublicMarksixNextRoute
  '/api/public/meeting-cancellation': typeof ApiPublicMeetingCancellationRoute
  '/api/public/telegram-alert': typeof ApiPublicTelegramAlertRoute
  '/api/public/weather-archive': typeof ApiPublicWeatherArchiveRoute
  '/api/public/weather-sync-github': typeof ApiPublicWeatherSyncGithubRoute
  '/football/match/$matchKey': typeof FootballMatchMatchKeyRoute
  '/football/study/$matchId': typeof FootballStudyMatchIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/race-results-dispatch': typeof ApiPublicHooksRaceResultsDispatchRoute
  '/football/team/$div/$slug': typeof FootballTeamDivSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cards'
    | '/dashboard'
    | '/dev-log'
    | '/encyclopedia'
    | '/features'
    | '/freeze-ledger'
    | '/horse'
    | '/login'
    | '/manual'
    | '/marksix'
    | '/marksix-results'
    | '/media-credits'
    | '/membership'
    | '/pool-odds'
    | '/prediction-vs-result'
    | '/predictor'
    | '/race'
    | '/racing-health'
    | '/results'
    | '/schedule'
    | '/strategy-pnl'
    | '/track-record'
    | '/admin'
    | '/engine/backtest'
    | '/engine/features'
    | '/engine/monitor'
    | '/engine/residuals'
    | '/explain/$date'
    | '/football/dual-ledger'
    | '/football/engine'
    | '/football/explain'
    | '/football/features'
    | '/football/fixtures'
    | '/football/ingest-status'
    | '/football/match-vs-result'
    | '/football/prediction-vs-result'
    | '/football/results'
    | '/football/standings'
    | '/football/study'
    | '/engine/'
    | '/explain/'
    | '/football/'
    | '/admin/console'
    | '/admin/data-freshness'
    | '/admin/engine-health'
    | '/admin/logs'
    | '/admin/model-versions'
    | '/admin/overview'
    | '/admin/pnl'
    | '/admin/prediction-lock'
    | '/admin/settings'
    | '/admin/users-membership'
    | '/api/public/data-mirror'
    | '/api/public/draw-tune'
    | '/api/public/engine-health'
    | '/api/public/football-crests'
    | '/api/public/football-dual-lock'
    | '/api/public/football-hkjc-list'
    | '/api/public/football-ingest-status'
    | '/api/public/football-league'
    | '/api/public/football-lineup-settle'
    | '/api/public/football-live'
    | '/api/public/football-live-results'
    | '/api/public/football-news'
    | '/api/public/football-pitchapi-probe'
    | '/api/public/football-player-source-check'
    | '/api/public/football-predictions'
    | '/api/public/football-source-check'
    | '/api/public/freeze-ledger'
    | '/api/public/hkjc-weather'
    | '/api/public/horse-hr2'
    | '/api/public/lock-state'
    | '/api/public/marksix-data'
    | '/api/public/marksix-next'
    | '/api/public/meeting-cancellation'
    | '/api/public/telegram-alert'
    | '/api/public/weather-archive'
    | '/api/public/weather-sync-github'
    | '/football/match/$matchKey'
    | '/football/study/$matchId'
    | '/admin/'
    | '/api/public/hooks/race-results-dispatch'
    | '/football/team/$div/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cards'
    | '/dashboard'
    | '/dev-log'
    | '/encyclopedia'
    | '/features'
    | '/freeze-ledger'
    | '/horse'
    | '/login'
    | '/manual'
    | '/marksix'
    | '/marksix-results'
    | '/media-credits'
    | '/membership'
    | '/pool-odds'
    | '/prediction-vs-result'
    | '/predictor'
    | '/race'
    | '/racing-health'
    | '/results'
    | '/schedule'
    | '/strategy-pnl'
    | '/track-record'
    | '/engine/backtest'
    | '/engine/features'
    | '/engine/monitor'
    | '/engine/residuals'
    | '/explain/$date'
    | '/football/dual-ledger'
    | '/football/engine'
    | '/football/explain'
    | '/football/features'
    | '/football/fixtures'
    | '/football/ingest-status'
    | '/football/match-vs-result'
    | '/football/prediction-vs-result'
    | '/football/results'
    | '/football/standings'
    | '/football/study'
    | '/engine'
    | '/explain'
    | '/football'
    | '/admin/console'
    | '/admin/data-freshness'
    | '/admin/engine-health'
    | '/admin/logs'
    | '/admin/model-versions'
    | '/admin/overview'
    | '/admin/pnl'
    | '/admin/prediction-lock'
    | '/admin/settings'
    | '/admin/users-membership'
    | '/api/public/data-mirror'
    | '/api/public/draw-tune'
    | '/api/public/engine-health'
    | '/api/public/football-crests'
    | '/api/public/football-dual-lock'
    | '/api/public/football-hkjc-list'
    | '/api/public/football-ingest-status'
    | '/api/public/football-league'
    | '/api/public/football-lineup-settle'
    | '/api/public/football-live'
    | '/api/public/football-live-results'
    | '/api/public/football-news'
    | '/api/public/football-pitchapi-probe'
    | '/api/public/football-player-source-check'
    | '/api/public/football-predictions'
    | '/api/public/football-source-check'
    | '/api/public/freeze-ledger'
    | '/api/public/hkjc-weather'
    | '/api/public/horse-hr2'
    | '/api/public/lock-state'
    | '/api/public/marksix-data'
    | '/api/public/marksix-next'
    | '/api/public/meeting-cancellation'
    | '/api/public/telegram-alert'
    | '/api/public/weather-archive'
    | '/api/public/weather-sync-github'
    | '/football/match/$matchKey'
    | '/football/study/$matchId'
    | '/admin'
    | '/api/public/hooks/race-results-dispatch'
    | '/football/team/$div/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cards'
    | '/dashboard'
    | '/dev-log'
    | '/encyclopedia'
    | '/features'
    | '/freeze-ledger'
    | '/horse'
    | '/login'
    | '/manual'
    | '/marksix'
    | '/marksix-results'
    | '/media-credits'
    | '/membership'
    | '/pool-odds'
    | '/prediction-vs-result'
    | '/predictor'
    | '/race'
    | '/racing-health'
    | '/results'
    | '/schedule'
    | '/strategy-pnl'
    | '/track-record'
    | '/_authenticated/admin'
    | '/engine/backtest'
    | '/engine/features'
    | '/engine/monitor'
    | '/engine/residuals'
    | '/explain/$date'
    | '/football/dual-ledger'
    | '/football/engine'
    | '/football/explain'
    | '/football/features'
    | '/football/fixtures'
    | '/football/ingest-status'
    | '/football/match-vs-result'
    | '/football/prediction-vs-result'
    | '/football/results'
    | '/football/standings'
    | '/football/study'
    | '/engine/'
    | '/explain/'
    | '/football/'
    | '/_authenticated/admin/console'
    | '/_authenticated/admin/data-freshness'
    | '/_authenticated/admin/engine-health'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/model-versions'
    | '/_authenticated/admin/overview'
    | '/_authenticated/admin/pnl'
    | '/_authenticated/admin/prediction-lock'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users-membership'
    | '/api/public/data-mirror'
    | '/api/public/draw-tune'
    | '/api/public/engine-health'
    | '/api/public/football-crests'
    | '/api/public/football-dual-lock'
    | '/api/public/football-hkjc-list'
    | '/api/public/football-ingest-status'
    | '/api/public/football-league'
    | '/api/public/football-lineup-settle'
    | '/api/public/football-live'
    | '/api/public/football-live-results'
    | '/api/public/football-news'
    | '/api/public/football-pitchapi-probe'
    | '/api/public/football-player-source-check'
    | '/api/public/football-predictions'
    | '/api/public/football-source-check'
    | '/api/public/freeze-ledger'
    | '/api/public/hkjc-weather'
    | '/api/public/horse-hr2'
    | '/api/public/lock-state'
    | '/api/public/marksix-data'
    | '/api/public/marksix-next'
    | '/api/public/meeting-cancellation'
    | '/api/public/telegram-alert'
    | '/api/public/weather-archive'
    | '/api/public/weather-sync-github'
    | '/football/match/$matchKey'
    | '/football/study/$matchId'
    | '/_authenticated/admin/'
    | '/api/public/hooks/race-results-dispatch'
    | '/football/team/$div/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CardsRoute: typeof CardsRoute
  DashboardRoute: typeof DashboardRoute
  DevLogRoute: typeof DevLogRoute
  EncyclopediaRoute: typeof EncyclopediaRoute
  FeaturesRoute: typeof FeaturesRoute
  FreezeLedgerRoute: typeof FreezeLedgerRoute
  HorseRoute: typeof HorseRoute
  LoginRoute: typeof LoginRoute
  ManualRoute: typeof ManualRoute
  MarksixRoute: typeof MarksixRoute
  MarksixResultsRoute: typeof MarksixResultsRoute
  MediaCreditsRoute: typeof MediaCreditsRoute
  MembershipRoute: typeof MembershipRoute
  PoolOddsRoute: typeof PoolOddsRoute
  PredictionVsResultRoute: typeof PredictionVsResultRoute
  PredictorRoute: typeof PredictorRoute
  RaceRoute: typeof RaceRoute
  RacingHealthRoute: typeof RacingHealthRoute
  ResultsRoute: typeof ResultsRoute
  ScheduleRoute: typeof ScheduleRoute
  StrategyPnlRoute: typeof StrategyPnlRoute
  TrackRecordRoute: typeof TrackRecordRoute
  EngineBacktestRoute: typeof EngineBacktestRoute
  EngineFeaturesRoute: typeof EngineFeaturesRoute
  EngineMonitorRoute: typeof EngineMonitorRoute
  EngineResidualsRoute: typeof EngineResidualsRoute
  ExplainDateRoute: typeof ExplainDateRoute
  FootballDualLedgerRoute: typeof FootballDualLedgerRoute
  FootballEngineRoute: typeof FootballEngineRoute
  FootballExplainRoute: typeof FootballExplainRoute
  FootballFeaturesRoute: typeof FootballFeaturesRoute
  FootballFixturesRoute: typeof FootballFixturesRoute
  FootballIngestStatusRoute: typeof FootballIngestStatusRoute
  FootballMatchVsResultRoute: typeof FootballMatchVsResultRoute
  FootballPredictionVsResultRoute: typeof FootballPredictionVsResultRoute
  FootballResultsRoute: typeof FootballResultsRoute
  FootballStandingsRoute: typeof FootballStandingsRoute
  FootballStudyRoute: typeof FootballStudyRouteWithChildren
  EngineIndexRoute: typeof EngineIndexRoute
  ExplainIndexRoute: typeof ExplainIndexRoute
  FootballIndexRoute: typeof FootballIndexRoute
  ApiPublicDataMirrorRoute: typeof ApiPublicDataMirrorRoute
  ApiPublicDrawTuneRoute: typeof ApiPublicDrawTuneRoute
  ApiPublicEngineHealthRoute: typeof ApiPublicEngineHealthRoute
  ApiPublicFootballCrestsRoute: typeof ApiPublicFootballCrestsRoute
  ApiPublicFootballDualLockRoute: typeof ApiPublicFootballDualLockRoute
  ApiPublicFootballHkjcListRoute: typeof ApiPublicFootballHkjcListRoute
  ApiPublicFootballIngestStatusRoute: typeof ApiPublicFootballIngestStatusRoute
  ApiPublicFootballLeagueRoute: typeof ApiPublicFootballLeagueRoute
  ApiPublicFootballLineupSettleRoute: typeof ApiPublicFootballLineupSettleRoute
  ApiPublicFootballLiveRoute: typeof ApiPublicFootballLiveRoute
  ApiPublicFootballLiveResultsRoute: typeof ApiPublicFootballLiveResultsRoute
  ApiPublicFootballNewsRoute: typeof ApiPublicFootballNewsRoute
  ApiPublicFootballPitchapiProbeRoute: typeof ApiPublicFootballPitchapiProbeRoute
  ApiPublicFootballPlayerSourceCheckRoute: typeof ApiPublicFootballPlayerSourceCheckRoute
  ApiPublicFootballPredictionsRoute: typeof ApiPublicFootballPredictionsRoute
  ApiPublicFootballSourceCheckRoute: typeof ApiPublicFootballSourceCheckRoute
  ApiPublicFreezeLedgerRoute: typeof ApiPublicFreezeLedgerRoute
  ApiPublicHkjcWeatherRoute: typeof ApiPublicHkjcWeatherRoute
  ApiPublicHorseHr2Route: typeof ApiPublicHorseHr2Route
  ApiPublicLockStateRoute: typeof ApiPublicLockStateRoute
  ApiPublicMarksixDataRoute: typeof ApiPublicMarksixDataRoute
  ApiPublicMarksixNextRoute: typeof ApiPublicMarksixNextRoute
  ApiPublicMeetingCancellationRoute: typeof ApiPublicMeetingCancellationRoute
  ApiPublicTelegramAlertRoute: typeof ApiPublicTelegramAlertRoute
  ApiPublicWeatherArchiveRoute: typeof ApiPublicWeatherArchiveRoute
  ApiPublicWeatherSyncGithubRoute: typeof ApiPublicWeatherSyncGithubRoute
  FootballMatchMatchKeyRoute: typeof FootballMatchMatchKeyRoute
  ApiPublicHooksRaceResultsDispatchRoute: typeof ApiPublicHooksRaceResultsDispatchRoute
  FootballTeamDivSlugRoute: typeof FootballTeamDivSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-log': {
      id: '/dev-log'
      path: '/dev-log'
      fullPath: '/dev-log'
      preLoaderRoute: typeof DevLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encyclopedia': {
      id: '/encyclopedia'
      path: '/encyclopedia'
      fullPath: '/encyclopedia'
      preLoaderRoute: typeof EncyclopediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freeze-ledger': {
      id: '/freeze-ledger'
      path: '/freeze-ledger'
      fullPath: '/freeze-ledger'
      preLoaderRoute: typeof FreezeLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horse': {
      id: '/horse'
      path: '/horse'
      fullPath: '/horse'
      preLoaderRoute: typeof HorseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marksix': {
      id: '/marksix'
      path: '/marksix'
      fullPath: '/marksix'
      preLoaderRoute: typeof MarksixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marksix-results': {
      id: '/marksix-results'
      path: '/marksix-results'
      fullPath: '/marksix-results'
      preLoaderRoute: typeof MarksixResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-credits': {
      id: '/media-credits'
      path: '/media-credits'
      fullPath: '/media-credits'
      preLoaderRoute: typeof MediaCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool-odds': {
      id: '/pool-odds'
      path: '/pool-odds'
      fullPath: '/pool-odds'
      preLoaderRoute: typeof PoolOddsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prediction-vs-result': {
      id: '/prediction-vs-result'
      path: '/prediction-vs-result'
      fullPath: '/prediction-vs-result'
      preLoaderRoute: typeof PredictionVsResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictor': {
      id: '/predictor'
      path: '/predictor'
      fullPath: '/predictor'
      preLoaderRoute: typeof PredictorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/race': {
      id: '/race'
      path: '/race'
      fullPath: '/race'
      preLoaderRoute: typeof RaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/racing-health': {
      id: '/racing-health'
      path: '/racing-health'
      fullPath: '/racing-health'
      preLoaderRoute: typeof RacingHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy-pnl': {
      id: '/strategy-pnl'
      path: '/strategy-pnl'
      fullPath: '/strategy-pnl'
      preLoaderRoute: typeof StrategyPnlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-record': {
      id: '/track-record'
      path: '/track-record'
      fullPath: '/track-record'
      preLoaderRoute: typeof TrackRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/engine/': {
      id: '/engine/'
      path: '/engine'
      fullPath: '/engine/'
      preLoaderRoute: typeof EngineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine/backtest': {
      id: '/engine/backtest'
      path: '/engine/backtest'
      fullPath: '/engine/backtest'
      preLoaderRoute: typeof EngineBacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine/features': {
      id: '/engine/features'
      path: '/engine/features'
      fullPath: '/engine/features'
      preLoaderRoute: typeof EngineFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine/monitor': {
      id: '/engine/monitor'
      path: '/engine/monitor'
      fullPath: '/engine/monitor'
      preLoaderRoute: typeof EngineMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine/residuals': {
      id: '/engine/residuals'
      path: '/engine/residuals'
      fullPath: '/engine/residuals'
      preLoaderRoute: typeof EngineResidualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explain/': {
      id: '/explain/'
      path: '/explain'
      fullPath: '/explain/'
      preLoaderRoute: typeof ExplainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explain/$date': {
      id: '/explain/$date'
      path: '/explain/$date'
      fullPath: '/explain/$date'
      preLoaderRoute: typeof ExplainDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football/': {
      id: '/football/'
      path: '/football'
      fullPath: '/football/'
      preLoaderRoute: typeof FootballIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football/dual-ledger': {
      id: '/football/dual-ledger'
      path: '/football/dual-ledger'
      fullPath: '/football/dual-ledger'
      preLoaderRoute: typeof FootballDualLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football/engine': {
      id: '/football/engine'
      path: '/football/engine'
      fullPath: '/football/engine'
      preLoaderRoute: typeof FootballEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football/explain': {
      id: '/football/explain'
      path: '/football/explain'
      fullPath: '/football/explain'
      preLoaderRoute: typeof FootballExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football/features': {
      id: '/football/features'
      path: '/football/features'
      fullPath: '/football/features'
      preLoaderRoute: typeof FootballFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football/fixtures': {
      id: '/football/fixtures'
      path: '/football/fixtures'
      fullPath: '/football/fixtures'
      preLoaderRoute: typeof FootballFixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football/ingest-status': {
      id: '/football/ingest-status'
      path: '/football/ingest-status'
      fullPath: '/football/ingest-status'
      preLoaderRoute: typeof FootballIngestStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football/match-vs-result': {
      id: '/football/match-vs-result'
      path: '/football/match-vs-result'
      fullPath: '/football/match-vs-result'
      preLoaderRoute: typeof FootballMatchVsResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football/prediction-vs-result': {
      id: '/football/prediction-vs-result'
      path: '/football/prediction-vs-result'
      fullPath: '/football/prediction-vs-result'
      preLoaderRoute: typeof FootballPredictionVsResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football/results': {
      id: '/football/results'
      path: '/football/results'
      fullPath: '/football/results'
      preLoaderRoute: typeof FootballResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football/standings': {
      id: '/football/standings'
      path: '/football/standings'
      fullPath: '/football/standings'
      preLoaderRoute: typeof FootballStandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football/study': {
      id: '/football/study'
      path: '/football/study'
      fullPath: '/football/study'
      preLoaderRoute: typeof FootballStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/console': {
      id: '/_authenticated/admin/console'
      path: '/console'
      fullPath: '/admin/console'
      preLoaderRoute: typeof AuthenticatedAdminConsoleRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/data-freshness': {
      id: '/_authenticated/admin/data-freshness'
      path: '/data-freshness'
      fullPath: '/admin/data-freshness'
      preLoaderRoute: typeof AuthenticatedAdminDataFreshnessRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/engine-health': {
      id: '/_authenticated/admin/engine-health'
      path: '/engine-health'
      fullPath: '/admin/engine-health'
      preLoaderRoute: typeof AuthenticatedAdminEngineHealthRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/model-versions': {
      id: '/_authenticated/admin/model-versions'
      path: '/model-versions'
      fullPath: '/admin/model-versions'
      preLoaderRoute: typeof AuthenticatedAdminModelVersionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/overview': {
      id: '/_authenticated/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AuthenticatedAdminOverviewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pnl': {
      id: '/_authenticated/admin/pnl'
      path: '/pnl'
      fullPath: '/admin/pnl'
      preLoaderRoute: typeof AuthenticatedAdminPnlRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/prediction-lock': {
      id: '/_authenticated/admin/prediction-lock'
      path: '/prediction-lock'
      fullPath: '/admin/prediction-lock'
      preLoaderRoute: typeof AuthenticatedAdminPredictionLockRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users-membership': {
      id: '/_authenticated/admin/users-membership'
      path: '/users-membership'
      fullPath: '/admin/users-membership'
      preLoaderRoute: typeof AuthenticatedAdminUsersMembershipRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/data-mirror': {
      id: '/api/public/data-mirror'
      path: '/api/public/data-mirror'
      fullPath: '/api/public/data-mirror'
      preLoaderRoute: typeof ApiPublicDataMirrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/draw-tune': {
      id: '/api/public/draw-tune'
      path: '/api/public/draw-tune'
      fullPath: '/api/public/draw-tune'
      preLoaderRoute: typeof ApiPublicDrawTuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/engine-health': {
      id: '/api/public/engine-health'
      path: '/api/public/engine-health'
      fullPath: '/api/public/engine-health'
      preLoaderRoute: typeof ApiPublicEngineHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/football-crests': {
      id: '/api/public/football-crests'
      path: '/api/public/football-crests'
      fullPath: '/api/public/football-crests'
      preLoaderRoute: typeof ApiPublicFootballCrestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/football-dual-lock': {
      id: '/api/public/football-dual-lock'
      path: '/api/public/football-dual-lock'
      fullPath: '/api/public/football-dual-lock'
      preLoaderRoute: typeof ApiPublicFootballDualLockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/football-hkjc-list': {
      id: '/api/public/football-hkjc-list'
      path: '/api/public/football-hkjc-list'
      fullPath: '/api/public/football-hkjc-list'
      preLoaderRoute: typeof ApiPublicFootballHkjcListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/football-ingest-status': {
      id: '/api/public/football-ingest-status'
      path: '/api/public/football-ingest-status'
      fullPath: '/api/public/football-ingest-status'
      preLoaderRoute: typeof ApiPublicFootballIngestStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/football-league': {
      id: '/api/public/football-league'
      path: '/api/public/football-league'
      fullPath: '/api/public/football-league'
      preLoaderRoute: typeof ApiPublicFootballLeagueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/football-lineup-settle': {
      id: '/api/public/football-lineup-settle'
      path: '/api/public/football-lineup-settle'
      fullPath: '/api/public/football-lineup-settle'
      preLoaderRoute: typeof ApiPublicFootballLineupSettleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/football-live': {
      id: '/api/public/football-live'
      path: '/api/public/football-live'
      fullPath: '/api/public/football-live'
      preLoaderRoute: typeof ApiPublicFootballLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/football-live-results': {
      id: '/api/public/football-live-results'
      path: '/api/public/football-live-results'
      fullPath: '/api/public/football-live-results'
      preLoaderRoute: typeof ApiPublicFootballLiveResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/football-news': {
      id: '/api/public/football-news'
      path: '/api/public/football-news'
      fullPath: '/api/public/football-news'
      preLoaderRoute: typeof ApiPublicFootballNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/football-pitchapi-probe': {
      id: '/api/public/football-pitchapi-probe'
      path: '/api/public/football-pitchapi-probe'
      fullPath: '/api/public/football-pitchapi-probe'
      preLoaderRoute: typeof ApiPublicFootballPitchapiProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/football-player-source-check': {
      id: '/api/public/football-player-source-check'
      path: '/api/public/football-player-source-check'
      fullPath: '/api/public/football-player-source-check'
      preLoaderRoute: typeof ApiPublicFootballPlayerSourceCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/football-predictions': {
      id: '/api/public/football-predictions'
      path: '/api/public/football-predictions'
      fullPath: '/api/public/football-predictions'
      preLoaderRoute: typeof ApiPublicFootballPredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/football-source-check': {
      id: '/api/public/football-source-check'
      path: '/api/public/football-source-check'
      fullPath: '/api/public/football-source-check'
      preLoaderRoute: typeof ApiPublicFootballSourceCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/freeze-ledger': {
      id: '/api/public/freeze-ledger'
      path: '/api/public/freeze-ledger'
      fullPath: '/api/public/freeze-ledger'
      preLoaderRoute: typeof ApiPublicFreezeLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hkjc-weather': {
      id: '/api/public/hkjc-weather'
      path: '/api/public/hkjc-weather'
      fullPath: '/api/public/hkjc-weather'
      preLoaderRoute: typeof ApiPublicHkjcWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/horse-hr2': {
      id: '/api/public/horse-hr2'
      path: '/api/public/horse-hr2'
      fullPath: '/api/public/horse-hr2'
      preLoaderRoute: typeof ApiPublicHorseHr2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lock-state': {
      id: '/api/public/lock-state'
      path: '/api/public/lock-state'
      fullPath: '/api/public/lock-state'
      preLoaderRoute: typeof ApiPublicLockStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/marksix-data': {
      id: '/api/public/marksix-data'
      path: '/api/public/marksix-data'
      fullPath: '/api/public/marksix-data'
      preLoaderRoute: typeof ApiPublicMarksixDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/marksix-next': {
      id: '/api/public/marksix-next'
      path: '/api/public/marksix-next'
      fullPath: '/api/public/marksix-next'
      preLoaderRoute: typeof ApiPublicMarksixNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meeting-cancellation': {
      id: '/api/public/meeting-cancellation'
      path: '/api/public/meeting-cancellation'
      fullPath: '/api/public/meeting-cancellation'
      preLoaderRoute: typeof ApiPublicMeetingCancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram-alert': {
      id: '/api/public/telegram-alert'
      path: '/api/public/telegram-alert'
      fullPath: '/api/public/telegram-alert'
      preLoaderRoute: typeof ApiPublicTelegramAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/weather-archive': {
      id: '/api/public/weather-archive'
      path: '/api/public/weather-archive'
      fullPath: '/api/public/weather-archive'
      preLoaderRoute: typeof ApiPublicWeatherArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/weather-sync-github': {
      id: '/api/public/weather-sync-github'
      path: '/api/public/weather-sync-github'
      fullPath: '/api/public/weather-sync-github'
      preLoaderRoute: typeof ApiPublicWeatherSyncGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football/match/$matchKey': {
      id: '/football/match/$matchKey'
      path: '/football/match/$matchKey'
      fullPath: '/football/match/$matchKey'
      preLoaderRoute: typeof FootballMatchMatchKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football/study/$matchId': {
      id: '/football/study/$matchId'
      path: '/$matchId'
      fullPath: '/football/study/$matchId'
      preLoaderRoute: typeof FootballStudyMatchIdRouteImport
      parentRoute: typeof FootballStudyRoute
    }
    '/api/public/hooks/race-results-dispatch': {
      id: '/api/public/hooks/race-results-dispatch'
      path: '/api/public/hooks/race-results-dispatch'
      fullPath: '/api/public/hooks/race-results-dispatch'
      preLoaderRoute: typeof ApiPublicHooksRaceResultsDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/football/team/$div/$slug': {
      id: '/football/team/$div/$slug'
      path: '/football/team/$div/$slug'
      fullPath: '/football/team/$div/$slug'
      preLoaderRoute: typeof FootballTeamDivSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminConsoleRoute: typeof AuthenticatedAdminConsoleRoute
  AuthenticatedAdminDataFreshnessRoute: typeof AuthenticatedAdminDataFreshnessRoute
  AuthenticatedAdminEngineHealthRoute: typeof AuthenticatedAdminEngineHealthRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminModelVersionsRoute: typeof AuthenticatedAdminModelVersionsRoute
  AuthenticatedAdminOverviewRoute: typeof AuthenticatedAdminOverviewRoute
  AuthenticatedAdminPnlRoute: typeof AuthenticatedAdminPnlRoute
  AuthenticatedAdminPredictionLockRoute: typeof AuthenticatedAdminPredictionLockRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersMembershipRoute: typeof AuthenticatedAdminUsersMembershipRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminConsoleRoute: AuthenticatedAdminConsoleRoute,
  AuthenticatedAdminDataFreshnessRoute: AuthenticatedAdminDataFreshnessRoute,
  AuthenticatedAdminEngineHealthRoute: AuthenticatedAdminEngineHealthRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminModelVersionsRoute: AuthenticatedAdminModelVersionsRoute,
  AuthenticatedAdminOverviewRoute: AuthenticatedAdminOverviewRoute,
  AuthenticatedAdminPnlRoute: AuthenticatedAdminPnlRoute,
  AuthenticatedAdminPredictionLockRoute: AuthenticatedAdminPredictionLockRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersMembershipRoute:
    AuthenticatedAdminUsersMembershipRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface FootballStudyRouteChildren {
  FootballStudyMatchIdRoute: typeof FootballStudyMatchIdRoute
}

const FootballStudyRouteChildren: FootballStudyRouteChildren = {
  FootballStudyMatchIdRoute: FootballStudyMatchIdRoute,
}

const FootballStudyRouteWithChildren = FootballStudyRoute._addFileChildren(
  FootballStudyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CardsRoute: CardsRoute,
  DashboardRoute: DashboardRoute,
  DevLogRoute: DevLogRoute,
  EncyclopediaRoute: EncyclopediaRoute,
  FeaturesRoute: FeaturesRoute,
  FreezeLedgerRoute: FreezeLedgerRoute,
  HorseRoute: HorseRoute,
  LoginRoute: LoginRoute,
  ManualRoute: ManualRoute,
  MarksixRoute: MarksixRoute,
  MarksixResultsRoute: MarksixResultsRoute,
  MediaCreditsRoute: MediaCreditsRoute,
  MembershipRoute: MembershipRoute,
  PoolOddsRoute: PoolOddsRoute,
  PredictionVsResultRoute: PredictionVsResultRoute,
  PredictorRoute: PredictorRoute,
  RaceRoute: RaceRoute,
  RacingHealthRoute: RacingHealthRoute,
  ResultsRoute: ResultsRoute,
  ScheduleRoute: ScheduleRoute,
  StrategyPnlRoute: StrategyPnlRoute,
  TrackRecordRoute: TrackRecordRoute,
  EngineBacktestRoute: EngineBacktestRoute,
  EngineFeaturesRoute: EngineFeaturesRoute,
  EngineMonitorRoute: EngineMonitorRoute,
  EngineResidualsRoute: EngineResidualsRoute,
  ExplainDateRoute: ExplainDateRoute,
  FootballDualLedgerRoute: FootballDualLedgerRoute,
  FootballEngineRoute: FootballEngineRoute,
  FootballExplainRoute: FootballExplainRoute,
  FootballFeaturesRoute: FootballFeaturesRoute,
  FootballFixturesRoute: FootballFixturesRoute,
  FootballIngestStatusRoute: FootballIngestStatusRoute,
  FootballMatchVsResultRoute: FootballMatchVsResultRoute,
  FootballPredictionVsResultRoute: FootballPredictionVsResultRoute,
  FootballResultsRoute: FootballResultsRoute,
  FootballStandingsRoute: FootballStandingsRoute,
  FootballStudyRoute: FootballStudyRouteWithChildren,
  EngineIndexRoute: EngineIndexRoute,
  ExplainIndexRoute: ExplainIndexRoute,
  FootballIndexRoute: FootballIndexRoute,
  ApiPublicDataMirrorRoute: ApiPublicDataMirrorRoute,
  ApiPublicDrawTuneRoute: ApiPublicDrawTuneRoute,
  ApiPublicEngineHealthRoute: ApiPublicEngineHealthRoute,
  ApiPublicFootballCrestsRoute: ApiPublicFootballCrestsRoute,
  ApiPublicFootballDualLockRoute: ApiPublicFootballDualLockRoute,
  ApiPublicFootballHkjcListRoute: ApiPublicFootballHkjcListRoute,
  ApiPublicFootballIngestStatusRoute: ApiPublicFootballIngestStatusRoute,
  ApiPublicFootballLeagueRoute: ApiPublicFootballLeagueRoute,
  ApiPublicFootballLineupSettleRoute: ApiPublicFootballLineupSettleRoute,
  ApiPublicFootballLiveRoute: ApiPublicFootballLiveRoute,
  ApiPublicFootballLiveResultsRoute: ApiPublicFootballLiveResultsRoute,
  ApiPublicFootballNewsRoute: ApiPublicFootballNewsRoute,
  ApiPublicFootballPitchapiProbeRoute: ApiPublicFootballPitchapiProbeRoute,
  ApiPublicFootballPlayerSourceCheckRoute:
    ApiPublicFootballPlayerSourceCheckRoute,
  ApiPublicFootballPredictionsRoute: ApiPublicFootballPredictionsRoute,
  ApiPublicFootballSourceCheckRoute: ApiPublicFootballSourceCheckRoute,
  ApiPublicFreezeLedgerRoute: ApiPublicFreezeLedgerRoute,
  ApiPublicHkjcWeatherRoute: ApiPublicHkjcWeatherRoute,
  ApiPublicHorseHr2Route: ApiPublicHorseHr2Route,
  ApiPublicLockStateRoute: ApiPublicLockStateRoute,
  ApiPublicMarksixDataRoute: ApiPublicMarksixDataRoute,
  ApiPublicMarksixNextRoute: ApiPublicMarksixNextRoute,
  ApiPublicMeetingCancellationRoute: ApiPublicMeetingCancellationRoute,
  ApiPublicTelegramAlertRoute: ApiPublicTelegramAlertRoute,
  ApiPublicWeatherArchiveRoute: ApiPublicWeatherArchiveRoute,
  ApiPublicWeatherSyncGithubRoute: ApiPublicWeatherSyncGithubRoute,
  FootballMatchMatchKeyRoute: FootballMatchMatchKeyRoute,
  ApiPublicHooksRaceResultsDispatchRoute:
    ApiPublicHooksRaceResultsDispatchRoute,
  FootballTeamDivSlugRoute: FootballTeamDivSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
